### ISSUE TITLE
Wrong Songs in FireRed

### ISSUE THREAD

**Issue by thewhitepikachu** [pret/pokefirered#320] opened 2020-04-04 10:34 UTC
Hello , i just recently came across your blog and in the end , here, because i wanted to hack some pokemon game rom's so i can make my own custom changes and also go even a little deeper.

So, while i came across your blog, i also have came across the FireRed and LeafGreen source codes, which is awesome, but while i was checking them , i realised that the folder with the Songs, has the wrong music , is not the music from FireRed/LeafGreen, but Emerald.

Could you check and upload the corect Songs ? , if you still got the Source Codes.
But either way , is fine, i mostly took the source code to see how it's writen, and to see the scripting part, because i want to custom that but i don't understand it very well yet.

Thanks.

**Comment by PikalaxALT** [comment] 2020-04-04 11:56
Please elaborate on specifically which songs are incorrect. The FRLG music is there, I guarantee it.

**Comment by thewhitepikachu** [comment] 2020-04-04 15:41
All of sounds (music) are from Emerald.
Archive pokefirered-master
Address : sound / songs / midi.
Play them with winamp and see, i knew they are from Emerald because i played the gym fight song, and i was , ok, this is not kanto gym fight song, it's Emerald.

**Comment by ProjectRevoTPP** [comment] 2020-04-04 15:47
Please join our discord at https://discord.gg/d5dubZ3 and I will inform you on why this is a very wrong train of thought.

**Comment by PikalaxALT** [comment] 2020-04-04 16:22
This issue was caused by a misunderstanding of how MIDI soundfonts work. Closing.

**Closed by PikalaxALT** 2020-04-04 16:22 UTC
